#!/bin/bash

# LAZI CRM - Environment Converter Script
# Converts production .env to local development .env.local

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Check if input file is provided
if [ -z "$1" ]; then
    echo -e "${RED}Error: No input file provided${NC}"
    echo ""
    echo "Usage: $0 <path-to-production-.env>"
    echo ""
    echo "Example:"
    echo "  $0 ../.env"
    echo "  $0 /path/to/production/.env"
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="$(dirname "$0")/../.env.local"

# Check if input file exists
if [ ! -f "$INPUT_FILE" ]; then
    echo -e "${RED}Error: Input file not found: $INPUT_FILE${NC}"
    exit 1
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      LAZI CRM - Environment Variable Converter             ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Input:  ${CYAN}$INPUT_FILE${NC}"
echo -e "Output: ${CYAN}$OUTPUT_FILE${NC}"
echo ""

# Backup existing .env.local if it exists
if [ -f "$OUTPUT_FILE" ]; then
    BACKUP_FILE="${OUTPUT_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$OUTPUT_FILE" "$BACKUP_FILE"
    echo -e "${YELLOW}⚠ Backed up existing .env.local to: $BACKUP_FILE${NC}"
    echo ""
fi

# Initialize counters
CHANGED_COUNT=0
UNCHANGED_COUNT=0
SKIPPED_COUNT=0

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
# ===========================================
# LAZI CRM - Local Development Environment
# ===========================================
# Generated by convert-env.sh
# DO NOT commit this file to version control
#
# This file contains environment variables for local development.
# Production values have been converted to localhost equivalents.
# ===========================================

EOF

echo -e "${BLUE}Processing environment variables...${NC}"
echo ""

# Arrays to track changes
declare -a CHANGED_VARS
declare -a UNCHANGED_VARS
declare -a SKIPPED_VARS

# Process each line
while IFS= read -r line; do
    # Skip empty lines and comments
    if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
        echo "$line" >> "$OUTPUT_FILE"
        continue
    fi
    
    # Extract variable name and value
    if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
        VAR_NAME="${BASH_REMATCH[1]}"
        VAR_VALUE="${BASH_REMATCH[2]}"
        
        # Remove leading/trailing whitespace from variable name
        VAR_NAME=$(echo "$VAR_NAME" | xargs)
        
        # Skip Traefik and SSL variables
        if [[ "$VAR_NAME" =~ ^TRAEFIK_ ]] || \
           [[ "$VAR_NAME" =~ ^ACME_ ]] || \
           [[ "$VAR_NAME" =~ ^LETSENCRYPT_ ]]; then
            SKIPPED_VARS+=("$VAR_NAME")
            ((SKIPPED_COUNT++))
            continue
        fi
        
        # Variables to convert
        CONVERTED=false
        
        # REDIS_URL
        if [[ "$VAR_NAME" == "REDIS_URL" ]]; then
            echo "${VAR_NAME}=redis://localhost:6379" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → redis://localhost:6379")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # ST_AUTOMATION_URL
        elif [[ "$VAR_NAME" == "ST_AUTOMATION_URL" ]]; then
            echo "${VAR_NAME}=http://localhost:3001" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3001")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # NEXT_PUBLIC_API_URL
        elif [[ "$VAR_NAME" == "NEXT_PUBLIC_API_URL" ]]; then
            echo "${VAR_NAME}=http://localhost:3001/api" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3001/api")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # NEXT_PUBLIC_APP_URL
        elif [[ "$VAR_NAME" == "NEXT_PUBLIC_APP_URL" ]]; then
            echo "${VAR_NAME}=http://localhost:3000" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3000")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # NEXT_PUBLIC_SOCKET_URL
        elif [[ "$VAR_NAME" == "NEXT_PUBLIC_SOCKET_URL" ]]; then
            echo "${VAR_NAME}=http://localhost:3001" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3001")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # NODE_ENV
        elif [[ "$VAR_NAME" == "NODE_ENV" ]]; then
            echo "${VAR_NAME}=development" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → development")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # CORS_ORIGINS
        elif [[ "$VAR_NAME" == "CORS_ORIGINS" ]]; then
            echo "${VAR_NAME}=http://localhost:3000,http://127.0.0.1:3000" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3000,http://127.0.0.1:3000")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # PLAID_REDIRECT_URI
        elif [[ "$VAR_NAME" == "PLAID_REDIRECT_URI" ]]; then
            echo "${VAR_NAME}=http://localhost:3000/api/plaid/oauth-redirect" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → http://localhost:3000/api/plaid/oauth-redirect")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # PLAID_ENV (set to sandbox for local dev)
        elif [[ "$VAR_NAME" == "PLAID_ENV" ]]; then
            echo "${VAR_NAME}=sandbox" >> "$OUTPUT_FILE"
            CHANGED_VARS+=("$VAR_NAME: $VAR_VALUE → sandbox")
            ((CHANGED_COUNT++))
            CONVERTED=true
        
        # Keep unchanged: DATABASE_URL, SERVICE_TITAN_*, AWS_*, TWILIO_*, RESEND_*, PLAID_CLIENT_ID, PLAID_SECRET
        elif [[ "$VAR_NAME" == "DATABASE_URL" ]] || \
             [[ "$VAR_NAME" =~ ^SERVICE_TITAN_ ]] || \
             [[ "$VAR_NAME" =~ ^AWS_ ]] || \
             [[ "$VAR_NAME" =~ ^TWILIO_ ]] || \
             [[ "$VAR_NAME" =~ ^RESEND_ ]] || \
             [[ "$VAR_NAME" == "PLAID_CLIENT_ID" ]] || \
             [[ "$VAR_NAME" == "PLAID_SECRET" ]] || \
             [[ "$VAR_NAME" == "DEFAULT_TENANT_ID" ]] || \
             [[ "$VAR_NAME" =~ ^JWT_ ]] || \
             [[ "$VAR_NAME" =~ ^SESSION_ ]]; then
            echo "$line" >> "$OUTPUT_FILE"
            UNCHANGED_VARS+=("$VAR_NAME")
            ((UNCHANGED_COUNT++))
            CONVERTED=true
        fi
        
        # If not converted yet, keep as-is (unknown variables)
        if [ "$CONVERTED" = false ]; then
            echo "$line" >> "$OUTPUT_FILE"
            UNCHANGED_VARS+=("$VAR_NAME (unknown)")
            ((UNCHANGED_COUNT++))
        fi
    else
        # Line doesn't match variable pattern, keep as-is
        echo "$line" >> "$OUTPUT_FILE"
    fi
done < "$INPUT_FILE"

# Print summary
echo -e "${GREEN}✓ Conversion complete!${NC}"
echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Summary${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}Changed:${NC}   $CHANGED_COUNT variables"
echo -e "${CYAN}Unchanged:${NC} $UNCHANGED_COUNT variables"
echo -e "${YELLOW}Skipped:${NC}   $SKIPPED_COUNT variables (Traefik/SSL)"
echo ""

# Show changed variables
if [ ${#CHANGED_VARS[@]} -gt 0 ]; then
    echo -e "${GREEN}━━━ Changed Variables ━━━${NC}"
    for var in "${CHANGED_VARS[@]}"; do
        echo -e "  ${GREEN}✓${NC} $var"
    done
    echo ""
fi

# Show unchanged variables (important ones)
if [ ${#UNCHANGED_VARS[@]} -gt 0 ]; then
    echo -e "${CYAN}━━━ Unchanged Variables (kept from production) ━━━${NC}"
    IMPORTANT_UNCHANGED=()
    for var in "${UNCHANGED_VARS[@]}"; do
        if [[ "$var" =~ ^(DATABASE_URL|SERVICE_TITAN_|AWS_|TWILIO_|RESEND_|PLAID_CLIENT_ID|PLAID_SECRET|DEFAULT_TENANT_ID) ]]; then
            IMPORTANT_UNCHANGED+=("$var")
        fi
    done
    
    if [ ${#IMPORTANT_UNCHANGED[@]} -gt 0 ]; then
        for var in "${IMPORTANT_UNCHANGED[@]}"; do
            echo -e "  ${CYAN}→${NC} $var"
        done
    else
        echo -e "  ${CYAN}→${NC} (See .env.local for full list)"
    fi
    echo ""
fi

# Show skipped variables
if [ ${#SKIPPED_VARS[@]} -gt 0 ]; then
    echo -e "${YELLOW}━━━ Skipped Variables (not needed for local dev) ━━━${NC}"
    for var in "${SKIPPED_VARS[@]}"; do
        echo -e "  ${YELLOW}⊘${NC} $var"
    done
    echo ""
fi

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}✓ Created: $OUTPUT_FILE${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Review the generated .env.local file"
echo "  2. Add any missing variables if needed"
echo "  3. Start local services: docker-compose -f docker-compose.local.yml up -d"
echo "  4. Start development: pnpm dev"
echo ""
echo -e "${YELLOW}⚠ Important:${NC}"
echo "  - Do NOT commit .env.local to version control"
echo "  - Verify all sensitive credentials are correct"
echo "  - Update ServiceTitan OAuth callback URLs if needed"
echo ""
