// Supabase database types for the pricing schema
export type Database = {
  pricing: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          legal_name: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          country: string;
          timezone: string;
          currency: string;
          fiscal_year_start: number;
          working_days_per_year: number;
          weeks_per_year: number;
          default_billable_hours_per_day: number;
          target_annual_revenue: number;
          material_cost_percent: number;
          default_payroll_tax_rate: number;
          default_futa_rate: number;
          default_suta_rate: number;
          default_workers_comp_rate_field: number;
          default_workers_comp_rate_office: number;
          servicetitan_tenant_id: string | null;
          servicetitan_connected: boolean;
          servicetitan_last_sync: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["organizations"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["organizations"]["Insert"]>;
      };
      technicians: {
        Row: {
          id: string;
          organization_id: string;
          employee_number: string | null;
          first_name: string;
          last_name: string;
          display_name: string;
          role: string;
          status: "active" | "inactive" | "terminated" | "on_leave";
          email: string | null;
          phone: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          hire_date: string | null;
          termination_date: string | null;
          department: string | null;
          pay_type: "hourly" | "salary";
          base_pay_rate: number | null;
          annual_salary: number | null;
          overtime_multiplier: number;
          paid_hours_per_day: number;
          payroll_tax_rate: number | null;
          futa_rate: number | null;
          suta_rate: number | null;
          workers_comp_rate: number | null;
          health_insurance_monthly: number;
          dental_insurance_monthly: number;
          vision_insurance_monthly: number;
          life_insurance_monthly: number;
          retirement_401k_match_percent: number;
          hsa_contribution_monthly: number;
          other_benefits_monthly: number;
          assigned_vehicle_id: string | null;
          servicetitan_employee_id: string | null;
          calculated_annual_base_pay: number | null;
          calculated_total_burden_annual: number | null;
          calculated_burden_percent: number | null;
          calculated_billable_hours_per_year: number | null;
          calculated_true_cost_per_hour: number | null;
          calculated_efficiency_percent: number | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["technicians"]["Row"], "id" | "display_name" | "is_active" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["technicians"]["Insert"]>;
      };
      office_staff: {
        Row: {
          id: string;
          organization_id: string;
          employee_number: string | null;
          first_name: string;
          last_name: string;
          display_name: string;
          role: string;
          status: "active" | "inactive" | "terminated" | "on_leave";
          email: string | null;
          phone: string | null;
          hire_date: string | null;
          termination_date: string | null;
          department: string | null;
          pay_type: "hourly" | "salary";
          base_pay_rate: number | null;
          annual_salary: number | null;
          hours_per_week: number;
          payroll_tax_rate: number | null;
          futa_rate: number | null;
          suta_rate: number | null;
          workers_comp_rate: number | null;
          health_insurance_monthly: number;
          dental_insurance_monthly: number;
          vision_insurance_monthly: number;
          life_insurance_monthly: number;
          retirement_401k_match_percent: number;
          hsa_contribution_monthly: number;
          other_benefits_monthly: number;
          calculated_annual_base_pay: number | null;
          calculated_total_burden_annual: number | null;
          calculated_burden_percent: number | null;
          calculated_monthly_cost: number | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["office_staff"]["Row"], "id" | "display_name" | "is_active" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["office_staff"]["Insert"]>;
      };
      vehicles: {
        Row: {
          id: string;
          organization_id: string;
          year: number | null;
          make: string | null;
          model: string | null;
          trim: string | null;
          color: string | null;
          vin: string | null;
          license_plate: string | null;
          status: "active" | "reserve" | "maintenance" | "sold" | "totaled";
          assigned_driver_id: string | null;
          purchase_date: string | null;
          purchase_price: number | null;
          loan_balance: number;
          monthly_payment: number;
          loan_interest_rate: number | null;
          loan_term_months: number | null;
          market_value: number;
          insurance_monthly: number;
          fuel_monthly: number;
          maintenance_monthly: number;
          registration_annual: number;
          odometer_current: number | null;
          odometer_at_purchase: number | null;
          fuel_type: string;
          mpg_average: number | null;
          servicetitan_equipment_id: string | null;
          calculated_equity: number | null;
          calculated_total_monthly_cost: number | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["vehicles"]["Row"], "id" | "is_active" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["vehicles"]["Insert"]>;
      };
      expense_categories: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          icon: string;
          color: string;
          is_payroll: boolean;
          is_fleet: boolean;
          is_system: boolean;
          sort_order: number;
          is_collapsed: boolean;
          calculated_monthly_total: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["pricing"]["Tables"]["expense_categories"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["expense_categories"]["Insert"]>;
      };
      expense_items: {
        Row: {
          id: string;
          category_id: string;
          organization_id: string;
          name: string;
          description: string | null;
          vendor: string | null;
          amount: number;
          frequency: "monthly" | "annual" | "quarterly" | "weekly" | "one_time";
          calculated_monthly_amount: number | null;
          account_number: string | null;
          is_tax_deductible: boolean;
          tax_category: string | null;
          sort_order: number;
          is_active: boolean;
          effective_date: string | null;
          end_date: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["expense_items"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["expense_items"]["Insert"]>;
      };
      job_types: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string | null;
          description: string | null;
          min_hours: number;
          max_hours: number;
          typical_hours: number | null;
          target_gross_margin: number;
          member_discount_percent: number;
          material_gross_margin: number;
          flat_surcharge: number;
          calculated_hourly_rate: number | null;
          calculated_member_rate: number | null;
          calculated_min_invoice: number | null;
          calculated_material_markup: number | null;
          servicetitan_business_unit_id: string | null;
          color: string;
          icon: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["pricing"]["Tables"]["job_types"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["pricing"]["Tables"]["job_types"]["Insert"]>;
      };
      scenarios: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          snapshot_data: Record<string, unknown>;
          summary_tech_count: number | null;
          summary_staff_count: number | null;
          summary_vehicle_count: number | null;
          summary_avg_burden_percent: number | null;
          summary_avg_efficiency_percent: number | null;
          summary_avg_true_cost_per_hour: number | null;
          summary_fleet_cost_monthly: number | null;
          summary_overhead_monthly: number | null;
          summary_avg_hourly_rate: number | null;
          summary_projected_revenue: number | null;
          summary_projected_net_profit: number | null;
          summary_net_profit_percent: number | null;
          summary_break_even_monthly: number | null;
          is_baseline: boolean;
          is_active: boolean;
          created_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database["pricing"]["Tables"]["scenarios"]["Row"], "id" | "created_at">;
        Update: Partial<Database["pricing"]["Tables"]["scenarios"]["Insert"]>;
      };
    };
    Views: {
      v_technician_summary: {
        Row: {
          id: string;
          organization_id: string;
          display_name: string;
          role: string;
          status: string;
          pay_type: string;
          base_pay_rate: number | null;
          paid_hours_per_day: number;
          payroll_tax_rate: number;
          futa_rate: number;
          suta_rate: number;
          workers_comp_rate: number;
          insurance_monthly: number;
          retirement_401k_match_percent: number;
          other_benefits_monthly: number;
          paid_unproductive_hours: number;
          unpaid_unproductive_hours: number;
          billable_hours_per_day: number;
          assigned_vehicle_id: string | null;
          vehicle_monthly_cost: number | null;
          calculated_annual_base_pay: number | null;
          calculated_total_burden_annual: number | null;
          calculated_burden_percent: number | null;
          calculated_true_cost_per_hour: number | null;
          calculated_efficiency_percent: number | null;
        };
      };
    };
    Functions: {
      seed_org_defaults: {
        Args: { org_id: string };
        Returns: void;
      };
    };
  };
};
